# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "vendor/**/*"
    - "node_modules/**/*"
  NewCops: enable
  TargetRailsVersion: 7.2
  TargetRubyVersion: 3.2

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
